### ISSUE TITLE
There is a typo in the about dialog.

### ISSUE THREAD

**Issue by deavmi** [valerio-bozzolan/AcrylicPaint#25]
See ![[image](http://i.imgur.com/JlvhaWo.jpg)](http://i.imgur.com/JlvhaWo.jpg).

**Comment by marcogagino-22** [comment]
Thanks, I'll correct it immediately!

**Comment by deavmi** [comment]
Pleasure and thanks. Making this app really awesome.

**Comment by deavmi** [comment]
Dat fon't tho, is the new Comic Sans

**Comment by marcogagino-22** [comment]
Isn't it the default font of your device? I don't think we've changed it.

**Comment by deavmi** [comment]
On my device, no I have Open Sans, changed it, using some app, samsungs's default font is like Samsung Sans, although i don't think it is Sans, idk. I suck at fonts.

**Comment by deavmi** [comment]
>  I don't think we've changed it.

What do you mean?

**Comment by marcogagino-22** [comment]
![screenshot_2015-01-11-12-16-49](https://cloud.githubusercontent.com/assets/9293129/5695042/cf1a79aa-998b-11e4-91ac-ad3bad09879f.png)

On my android 5.0 nexus 5 I have this font. The font used in there is the device font you have set on your device.

**Comment by deavmi** [comment]
Lollipop. Noce.
