### ISSUE TITLE
Building Acrylic Paint with Gradle

### ISSUE THREAD

**Issue by aoiserizawa** [valerio-bozzolan/AcrylicPaint#27]
can I ask the gradle Dependency for this?

**Comment by valerio-bozzolan** [comment]
Sorry but this app is built with Ant, not Gradle. So can hack it with Eclipse and not with Android Studio.

It's in my wishlist to convert it to Gradle. Feel free to import this app with Android Studio in some way, I'll accept the pull request!

**Comment by valerio-bozzolan** [comment]
See #33

**Comment by valerio-bozzolan** [comment]
Please let me know if now you can import this project into Android Studio.
