### ISSUE TITLE
Clear all option should not reset current color 

### ISSUE THREAD

**Issue by brunetton** [valerio-bozzolan/AcrylicPaint#41]
When clearing the draw, I'm surprised that the selected color is reseted. I use this soft to draw a serie of drawings (maths notation), and I always use the same color. 
Thanks!

**Comment by TheOpenSourceNinja** [comment]
I believe I've fixed this. See pull request #42. I had to rewrite a few lines related to erasing the image.

**Comment by valerio-bozzolan** [comment]
@TheOpenSourceNinja Where are you from? Here it's 08:31! Do you work on Android projects during your breakfasts? :P

I'll review this ASAP. Thank you!

**Comment by TheOpenSourceNinja** [comment]
It's 23:36 now where I am; I should be getting to bed! :smiley: 
I do tend to work on programming projects late into the night. It's when I feel most creative.

**Comment by valerio-bozzolan** [comment]
(@TheOpenSourceNinja ↑ Absolutely. Trying to explain this to parents/friends since years.)

**Comment by valerio-bozzolan** [comment]
I think that it's fixed in 23e2b593381461fefd3333f27950d8e99af0b835 thanks to @TheOpenSourceNinja.

**Comment by TheOpenSourceNinja** [comment]
Glad I could help!
