### ISSUE TITLE
Is the plus sign in the following an error: android:icon="@+drawable/

### ISSUE THREAD

**Issue by mhurwicz** [valerio-bozzolan/AcrylicPaint#50]
In  /app/res/menu/main.xml ,  Android Studio 2.2.3 is giving me a "Cannot resolve symbol" error for each `icon` line.  If I remove the plus sign, that error goes away. But the app seems to work fine with the plus signs, too. Are the plus signs just plain wrong? Or is there something going on here that I don't understand?

http://stackoverflow.com/questions/41647704/is-the-plus-sign-in-the-following-an-error-androidicon-drawable

**Comment by TheOpenSourceNinja** [comment]
I too get the "cannot resolve symbol" error message. I've simply ignored it since the app compiles & runs anyway.

**Comment by mhurwicz** [comment]
Based on stackoverflow feedback, I'm deleting the + signs.

**Comment by valerio-bozzolan** [comment]
This project is now associated to a StackOverflow question about how inconsistency is Android Studio. 

Sounds good.

**Comment by valerio-bozzolan** [comment]
@mhurwicz Thanks, I think that we can keep this opened until a PR.

**Comment by mhurwicz** [comment]
Sorry, Valerio, I thought because of the label you applied and the comment you made that you considered this more a problem of Android Studio than AcrylicPaint. But I have now created a PR.

**Comment by valerio-bozzolan** [comment]
@mhurwicz Considering that the 98% of the time involved in this Android app is concerning Android Studio instead of in coding. Not a wontfix, only a "rant" :^)

Thanks, merged.
