### ISSUE TITLE
Open with intent containing the path to save to?

### ISSUE THREAD

**Issue by moovida** [valerio-bozzolan/AcrylicPaint#52]
Hi, I would love to use AcrylicPaint from within my GPL3 app Geopaparazzi to do sketches when out in the field. To do so, I would need the possibility to tell acrylic paint where to save the image once done.

So short question: is that currently possible? Thanks for any answer.
Nice nice app :-)

**Comment by valerio-bozzolan** [comment]
PRs are welcome ;)

(P.S. I'm also Italian!)

**Comment by moovida** [comment]
Hi @valerio-bozzolan , nice to hear from you. The fact that the project is Italian, makes me even happier.

In fact I looked into the code, and being that nice and clean I was able to already integrate acrylic paint into my app and am testing it a bit these days.

I would need to also coordinates of the position be passed through the intent and, is launched in "forresult" mode I would need that data to be returned. I am not sure if that is something you would want to "dirty" your app with, since it is very domain specific (I didn't think of this when I opened the issue).

If there is a real interest for this (and I understand if there is not) I can sure make a PR.

**Comment by valerio-bozzolan** [comment]
First of all I want to show my completely disagreement about the clean status of the Acrylic Paint source code :^) It is probably my worst app, together with  [MineSweeper](https://f-droid.org/repository/browse/?fdid=it.reyboz.minesweeper).

Feel free to submit what do you consider an enhancements: only avoid crashes :^)

(If you will visit Turin, don't forget [BusTO](https://f-droid.org/repository/browse/?fdid=it.reyboz.bustorino)!)
