### ISSUE TITLE
Updating the Android Build Tools and SDK Compile Version

### ISSUE THREAD

**Issue by AdamHooyer** [valerio-bozzolan/AcrylicPaint#61]
I was wondering if there is a reason for not updating the build tools and the compile version. I want to be able to run the project as intended and also maybe help fix some of the bugs. However, I'm getting errors when I put the project in Android Studio until I change the build tools and compile version. I'm guessing there is a reason for not updating, but I don't know what it is or how to deal with it. Also if this is not the best way to ask let me know where would be better to ask.

**Comment by valerio-bozzolan** [comment]
Hello @AdamHooyer!

If you have to update the build tools and the compile version to work on this app, please do so :)
