### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [valerio-bozzolan/AcrylicPaint#73]
You can add Screenshots for F-Droid, too, if you want.
https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/
https://gitlab.com/snippets/1895688

**Comment by valerio-bozzolan** [comment]
Have you some time to do some screenshots? I will be glad to accept your pull requests for this.

Somehow related to #40 O:)

**Comment by mondlicht-und-sterne** [comment]
I don't know anything about pull requests. 
If you have any, you would have to enter them in fastlane.

**Comment by valerio-bozzolan** [comment]
I mean that if you have the time to do some screenshots in a correct directory structure please send them in whatever way :)

Also a .tar.gz is OK.

Pick an email from:

https://boz.reyboz.it

Thank you

**Comment by mondlicht-und-sterne** [comment]
Since the issue dates back a long time - can you just close
the issue? Thank you, my initial Issie was also just information.

**Comment by valerio-bozzolan** [comment]
Feel free to close, but also feel free to upload here some screenshots :)

**Comment by mondlicht-und-sterne** [comment]
a day has only 24 hours, like yours
