### ISSUE TITLE
Please Add Black (& white?) Colours

### ISSUE THREAD

**Issue by EitanGilboa** [valerio-bozzolan/AcrylicPaint#75]
Hi, 

Strangely these colors are not available on the colour palette (or am I being stupid?)

Thanks,
EitanGilboa

**Comment by valerio-bozzolan** [comment]
Yes actually we have a stupid color picker :) Please join this thread: #46

Thank you!

**Comment by EitanGilboa** [comment]
Hi valerio-bozzolan,
Thanks for the quick reply !
Thread #46 dates back to 2016 !!! I gather that this means that you will keep the "stupid color picker :) " for ever ??? <BG>
 
Best Wishes,
Eitan Gilboa
----------------Le 08/02/2021, à 10:05, Valerio Bozzolan a écrit :
Yes actually we have a stupid color picker :) Please join this thread: #46
Thank you!

**Comment by valerio-bozzolan** [comment]
It just means that pull requests are welcome but actually nobody seems to have time to contribute to it.

You can be the first one!
